# Generated by Django 6.0.6 on 2026-07-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_interview_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='university_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
